import '../public/antd.min.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Layout } from 'antd';
import StyledComponentsRegistry from '../lib/AntdRegistry';
import Wrapper from '../components/wrapper/wrapper';
import MainHeader from '../components/header/header';
import MainFooter from '../components/footer/footer';
import Main from '../components/main/main';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Kiddo Kingdom',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: 0 }}>
        <StyledComponentsRegistry>
          <Layout style={{ minHeight: '100vh' }}>
            <Wrapper>
              <MainHeader />
              <Main>{children}</Main>
              <MainFooter />
            </Wrapper>
          </Layout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
