import StyledComponentsRegistry from '../../lib/AntdRegistry';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return <StyledComponentsRegistry>{children}</StyledComponentsRegistry>;
}
